### ISSUE TITLE
Expose alignment to `avec![]` / deduce it automatically

### ISSUE THREAD

**Issue by SK83RJOSH** [sarah-ek/aligned-vec#2]
I really love this crate, but one of the more cumbersome aspects of it is the inability to create non-runtime aligned vectors conveniently. It would be really handy to be able to either deduce the alignment automatically, or specify it explicitly like so:

```rust
let vec: AVec<u8, ConstAlign<16>> = avec![0; 128];
let vec: AVec<u8> = avec![[16]| 0; 128];
```

**Comment by sarah-ek** [comment]
i haven't used anything other than the default const alignment (cacheline size) in practice :sweat_smile: 
is it something you use often?

**Comment by SK83RJOSH** [comment]
Indeed, I'm doing some homebrew at the moment and different types of graphics buffers need different alignment. For example, texture data needs to be 128-byte aligned for fast path rendering on the psp, and vertex detta must be 16-byte aligned for the SoC to do interpolation of vertex attributes. :)

**Comment by sarah-ek** [comment]
automatic deduction is gonna be a bit tricky, but i can do the second option i think

**Comment by sarah-ek** [comment]
added the second macro variant in 0.6.0
