### ISSUE TITLE
`Into`/`From` impls for `Vec`/`AVec`

### ISSUE THREAD

**Issue by SK83RJOSH** [sarah-ek/aligned-vec#3]
It would be really handy to be able to go from an unaligned vec to an aligned vec and vice versa like so:
```rust
let vec = vec![0_u8; 128];
let vec: AVec<_> = vec.into();
let vec: Vec<_> = vec.into();
```

Additionally, it would be handy to go between `AVec` of different alignment values in the same way:
```rust
let vec: AVec<_, ConstAlign<32>> = avec_rt![[16]| 0_u8; 128].into();
let vec: AVec<_, ConstAlign<16>> = avec_rt![[16]| 0_u8; 128].into();
```

**Comment by sarah-ek** [comment]
this is not possible in the general case, at least not without reallocating, since memory allocated with one alignment must be deallocated with the same alignment

**Comment by SK83RJOSH** [comment]
That's fine by me, it's just a nicety to make things less cumbersome ^^

**Comment by sarah-ek** [comment]
with const alignments, i think you can just always pass 0 as an alignment argument but i forgot. it's been a while since i worked on this crate :sweat_smile: 
it's also undocumented. i'll try to find some time to make that part easier to work with

**Comment by sarah-ek** [comment]
i documented the fact that you can pass in 0 as the alignment value, which will cause the vector to use the minimum possible alignment that satisfies both the type and alignment type requirements
