### ISSUE TITLE
Resize function is missing

### ISSUE THREAD

**Issue by AlexanderSchuetz97** [sarah-ek/aligned-vec#6]
I have a use case where I have a AVec with a inital size but later down the line I need to "grow" the AVec.
Ordinary Vec has a function called resize(desired_len, 0u8) for example.
I am aware that this may grow the AVec/Vec beyond capacity. In this case I would expect a new allocation to take place that is also
properly aligned.

Why do I need this?
The AVec is passed to c code as a ptr and I do know ahead of time how much data the c code will write to the vec.
I need to "set" the size of the AVec to that before or after the call. (Ideally before)

Could you add this function?

**Comment by sarah-ek** [comment]
sure, i'll add it in

**Comment by sarah-ek** [comment]
solved by #5
