### ISSUE TITLE
Alignment to page size is not working

### ISSUE THREAD

**Issue by AlexanderSchuetz97** [sarah-ek/aligned-vec#7]
Hello for my purpose alignment to page size is very important.
I have written this simple test to test if this library does what its supposed to.
It does not, the test fails:
```rust
let page_size = 4096; //Comes from the OS.

let mut aligned = AVec::<u8>::with_capacity(page_size, 24576);
while aligned.len() < aligned.capacity() {
    aligned.push(0u8);
}

assert_eq!(aligned.as_ptr().align_offset(page_size), 0);
```

**Comment by sarah-ek** [comment]
you need to use `Avec::<u8, RuntimeAlign>` i believe. since it's locked to the cache line size at compile time by default

**Comment by AlexanderSchuetz97** [comment]
I will test this on monday.
Also I recommend changing this api method so it works as I tryed to use it. It is your crates only purpose to create vec's where the assert mentioned above checks out.

Or alternatively make a second method and make this method panic if an argument is passed that for some reason cannot be aligned to. (Would have saved me a ton of debugging)

Im not faulting you for this but I blindly trusted your library to properly align the pointer today and spent 1-2 hours trying to find the fault in the c code that required the pointer to be aligned. (The c code does funny stuff with the actual pages, causing the funniest errors/behaviors if its not properly aligned) It was a odd moment when I realized that an aligned vec is not actually aligned and so the pointer is not aligned...

I have in the mean time switched to allocating a one page larger than normal vec and calculating the base ptr based on the random offset this vec would have to the page. This serves its purpose for now but does require cloneing the actual data part to return it. If your library works with the suggested fix, then I could just return AVec<u8> and call it a day.

**Comment by FreezyLemon** [comment]
https://github.com/sarah-ek/aligned-vec/blob/b52b2e78d940cda6622f99ffb8deb4c505e2635b/src/lib.rs#L114-L118

How about adding checks here? `assert_eq!(align, ALIGN);` etc.
It is a bit unexpected that these alignment parameters are just ignored.

BTW if you know the page size at compile-time, you can also do `AVec<T, ConstAlign<PAGE_SIZE_HERE>>`

**Comment by sarah-ek** [comment]
yeah. I'll add an assert. just been busy with real life stuff and haven't had time to do everything i wanna do ^^'

**Comment by AlexanderSchuetz97** [comment]
Im getting the pagesize from libc. To my knowlege the page size may vary depending on the kernel but its usually 4096. To be safe i just call getpagesize from libc crate. I would not really feel comfortable with hardcosing the alignment. Ive switched to use std::alloc to allocate my memory. It uses something called Layout and that does actually always properly align my value. The returned rawptr is turned into a slice for usage within rust after the c code is done. Unless this crate produces a reliablely aligned vec to whatever the pagesize is, its mot useful to me.

Feel free to close this issue if you want to.

**Comment by sarah-ek** [comment]
added an assert in 0.6.0

for your use case, i believe you can use `avec_rt![[page_size] | 0; size]`
