### ISSUE TITLE
Publish version 0.6.0 to crates.io

### ISSUE THREAD

**Issue by ffminus** [sarah-ek/aligned-vec#8]
Hello,

I'd like to publish a crate that uses `AVec::extend_from_slice`, which is available only from 0.6.0.

Would you mind publishing version 0.6.0 to crates.io please?

Happy to help or contribute if there is anything blocking the release.

Thanks

**Comment by sarah-ek** [comment]
there's no blockers. just haven't had much time to work on this project for a while. i'll try to find some time this week to finish the stuff on my todo list and publish the next release

**Comment by sarah-ek** [comment]
done!
